[2023-09-19 09:10:05,522] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_decision_tree 2023-09-19T09:08:54.555224+00:00 [queued]>
[2023-09-19 09:10:05,551] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_decision_tree 2023-09-19T09:08:54.555224+00:00 [queued]>
[2023-09-19 09:10:05,552] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:10:05,552] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 09:10:05,552] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:10:05,592] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): train_decision_tree> on 2023-09-19T09:08:54.555224+00:00
[2023-09-19 09:10:05,612] {standard_task_runner.py:52} INFO - Started process 1671 to run task
[2023-09-19 09:10:05,623] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_decision_tree', '2023-09-19T09:08:54.555224+00:00', '--job-id', '584', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpddaxnpjj', '--error-file', '/tmp/tmp9_vpymjw']
[2023-09-19 09:10:05,624] {standard_task_runner.py:77} INFO - Job 584: Subtask train_decision_tree
[2023-09-19 09:10:05,733] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.train_decision_tree 2023-09-19T09:08:54.555224+00:00 [running]> on host 92beb7708765
[2023-09-19 09:10:05,862] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=train_decision_tree
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T09:08:54.555224+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T09:08:54.555224+00:00
[2023-09-19 09:10:05,956] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:10:05,960] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:10:06,054] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:10:06,070] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:10:06,144] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:10:06,155] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:10:06,497] {python.py:151} INFO - Done. Returned value was: None
[2023-09-19 09:10:06,540] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_decision_tree, execution_date=20230919T090854, start_date=20230919T091005, end_date=20230919T091006
[2023-09-19 09:10:06,803] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19 09:10:06,891] {local_task_job.py:151} INFO - Task exited with return code 0
