[2023-09-19 09:24:09,294] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:22:54.555224+00:00 [queued]>
[2023-09-19 09:24:09,329] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:22:54.555224+00:00 [queued]>
[2023-09-19 09:24:09,330] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:24:09,330] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 09:24:09,330] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:24:09,357] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): train_random_forest> on 2023-09-19T09:22:54.555224+00:00
[2023-09-19 09:24:09,378] {standard_task_runner.py:52} INFO - Started process 2515 to run task
[2023-09-19 09:24:09,386] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_random_forest', '2023-09-19T09:22:54.555224+00:00', '--job-id', '682', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmp02i7ggb7', '--error-file', '/tmp/tmp2okpqngg']
[2023-09-19 09:24:09,387] {standard_task_runner.py:77} INFO - Job 682: Subtask train_random_forest
[2023-09-19 09:24:09,469] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:22:54.555224+00:00 [running]> on host 92beb7708765
[2023-09-19 09:24:09,652] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=train_random_forest
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T09:22:54.555224+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T09:22:54.555224+00:00
[2023-09-19 09:24:09,828] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:24:09,842] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:24:10,026] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:24:10,038] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:24:10,166] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:24:10,170] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:24:11,785] {python.py:151} INFO - Done. Returned value was: None
[2023-09-19 09:24:11,803] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_random_forest, execution_date=20230919T092254, start_date=20230919T092409, end_date=20230919T092411
[2023-09-19 09:24:11,856] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-09-19 09:24:11,899] {local_task_job.py:151} INFO - Task exited with return code 0
