[2023-09-19 09:22:07,601] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:20:54.555224+00:00 [queued]>
[2023-09-19 09:22:07,644] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:20:54.555224+00:00 [queued]>
[2023-09-19 09:22:07,644] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:22:07,644] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 09:22:07,645] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:22:07,721] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): train_random_forest> on 2023-09-19T09:20:54.555224+00:00
[2023-09-19 09:22:07,751] {standard_task_runner.py:52} INFO - Started process 2395 to run task
[2023-09-19 09:22:07,784] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_random_forest', '2023-09-19T09:20:54.555224+00:00', '--job-id', '667', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpycyfpdc5', '--error-file', '/tmp/tmp9n9vpxr8']
[2023-09-19 09:22:07,785] {standard_task_runner.py:77} INFO - Job 667: Subtask train_random_forest
[2023-09-19 09:22:07,947] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:20:54.555224+00:00 [running]> on host 92beb7708765
[2023-09-19 09:22:08,135] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=train_random_forest
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T09:20:54.555224+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T09:20:54.555224+00:00
[2023-09-19 09:22:08,345] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:22:08,370] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:22:08,485] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:22:08,489] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:22:08,576] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:22:08,588] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:22:10,220] {python.py:151} INFO - Done. Returned value was: None
[2023-09-19 09:22:10,236] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_random_forest, execution_date=20230919T092054, start_date=20230919T092207, end_date=20230919T092210
[2023-09-19 09:22:10,289] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-09-19 09:22:10,308] {local_task_job.py:151} INFO - Task exited with return code 0
