[2023-09-19 09:21:09,091] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:19:54.555224+00:00 [queued]>
[2023-09-19 09:21:09,193] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:19:54.555224+00:00 [queued]>
[2023-09-19 09:21:09,193] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:21:09,193] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 09:21:09,193] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:21:09,257] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): train_random_forest> on 2023-09-19T09:19:54.555224+00:00
[2023-09-19 09:21:09,274] {standard_task_runner.py:52} INFO - Started process 2332 to run task
[2023-09-19 09:21:09,294] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_random_forest', '2023-09-19T09:19:54.555224+00:00', '--job-id', '660', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmp_n28lnht', '--error-file', '/tmp/tmp2m1wfjfm']
[2023-09-19 09:21:09,294] {standard_task_runner.py:77} INFO - Job 660: Subtask train_random_forest
[2023-09-19 09:21:09,461] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.train_random_forest 2023-09-19T09:19:54.555224+00:00 [running]> on host 92beb7708765
[2023-09-19 09:21:09,654] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=train_random_forest
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T09:19:54.555224+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T09:19:54.555224+00:00
[2023-09-19 09:21:09,768] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:21:09,787] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:21:09,897] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:21:09,919] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:21:10,025] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:21:10,039] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:21:11,934] {python.py:151} INFO - Done. Returned value was: None
[2023-09-19 09:21:11,945] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_random_forest, execution_date=20230919T091954, start_date=20230919T092109, end_date=20230919T092111
[2023-09-19 09:21:11,981] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-09-19 09:21:12,001] {local_task_job.py:151} INFO - Task exited with return code 0
