[2023-09-19 09:08:35,958] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_linear_regression 2023-09-19T09:08:11.736735+00:00 [queued]>
[2023-09-19 09:08:36,042] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_linear_regression 2023-09-19T09:08:11.736735+00:00 [queued]>
[2023-09-19 09:08:36,042] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:08:36,042] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 09:08:36,043] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:08:36,124] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): train_linear_regression> on 2023-09-19T09:08:11.736735+00:00
[2023-09-19 09:08:36,160] {standard_task_runner.py:52} INFO - Started process 1570 to run task
[2023-09-19 09:08:36,189] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_linear_regression', '2023-09-19T09:08:11.736735+00:00', '--job-id', '571', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpse1pb1h4', '--error-file', '/tmp/tmpdsepz65n']
[2023-09-19 09:08:36,190] {standard_task_runner.py:77} INFO - Job 571: Subtask train_linear_regression
[2023-09-19 09:08:36,360] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.train_linear_regression 2023-09-19T09:08:11.736735+00:00 [running]> on host 92beb7708765
[2023-09-19 09:08:36,570] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=train_linear_regression
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T09:08:11.736735+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-19T09:08:11.736735+00:00
[2023-09-19 09:08:36,696] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:08:36,712] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:08:36,892] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:08:36,938] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:08:37,176] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:08:37,181] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:08:37,588] {python.py:151} INFO - Done. Returned value was: None
[2023-09-19 09:08:37,621] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_linear_regression, execution_date=20230919T090811, start_date=20230919T090835, end_date=20230919T090837
[2023-09-19 09:08:37,713] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19 09:08:37,748] {local_task_job.py:151} INFO - Task exited with return code 0
