[2023-09-19 09:09:08,759] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_linear_regression 2023-09-19T09:07:54.555224+00:00 [queued]>
[2023-09-19 09:09:08,838] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.train_linear_regression 2023-09-19T09:07:54.555224+00:00 [queued]>
[2023-09-19 09:09:08,838] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:09:08,838] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2023-09-19 09:09:08,838] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-09-19 09:09:08,898] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): train_linear_regression> on 2023-09-19T09:07:54.555224+00:00
[2023-09-19 09:09:08,925] {standard_task_runner.py:52} INFO - Started process 1606 to run task
[2023-09-19 09:09:08,957] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_linear_regression', '2023-09-19T09:07:54.555224+00:00', '--job-id', '577', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpvhf10xth', '--error-file', '/tmp/tmpsal14wu9']
[2023-09-19 09:09:08,957] {standard_task_runner.py:77} INFO - Job 577: Subtask train_linear_regression
[2023-09-19 09:09:09,134] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.train_linear_regression 2023-09-19T09:07:54.555224+00:00 [running]> on host 92beb7708765
[2023-09-19 09:09:09,314] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=train_linear_regression
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T09:07:54.555224+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T09:07:54.555224+00:00
[2023-09-19 09:09:09,398] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:09:09,402] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:09:09,483] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:09:09,495] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:09:09,584] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1596 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:09:09,588] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1743 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-09-19 09:09:09,789] {python.py:151} INFO - Done. Returned value was: None
[2023-09-19 09:09:09,816] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_linear_regression, execution_date=20230919T090754, start_date=20230919T090908, end_date=20230919T090909
[2023-09-19 09:09:09,880] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-19 09:09:09,902] {local_task_job.py:151} INFO - Task exited with return code 0
